// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC05AhKKGFz_8jZej7wvwtEq-8UX60FnF8',
    appId: '1:410872847420:web:076267804c1e65523b7739',
    messagingSenderId: '410872847420',
    projectId: 'black-chain-ad0bb',
    authDomain: 'black-chain-ad0bb.firebaseapp.com',
    storageBucket: 'black-chain-ad0bb.firebasestorage.app',
    measurementId: 'G-Y2E5J7TTNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiijBGEC5wuQkyAyeT2w-N_ozByuxW6kM',
    appId: '1:410872847420:android:65898264c9775bf63b7739',
    messagingSenderId: '410872847420',
    projectId: 'black-chain-ad0bb',
    storageBucket: 'black-chain-ad0bb.firebasestorage.app',
  );
}
